apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  namespace: apk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      containers:
      - name: envoy-proxy
        image: envoy-proxy:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
        ports:
        - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
  namespace: apk
spec:
  selector:
    app: envoy-proxy
  ports:
  - name: gateway
    protocol: TCP
    port: 9095
    targetPort: 9095
  - name: admin
    protocol: TCP
    port: 9901
    targetPort: 9901
