apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-server
  namespace: apk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-server
  template:
    metadata:
      labels:
        app: sse-server
    spec:
      containers:
      - name: sse-server
        image: sse-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sse-server
  namespace: apk
spec:
  selector:
    app: sse-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
